# Model Fit in Linear Regression - Lab

## Introduction
In this lab, you'll learn how to evaluate your model results and you'll learn how to select the appropriate features using stepwise selection.

## Objectives
You will be able to:
* Use stepwise selection methods to determine the most important features for a model
* Use recursive feature elimination to determine the most important features for a model

## The Ames Housing Data once more

In [15]:
import pandas as pd
import numpy as np

ames = pd.read_csv('ames.csv')

continuous = ['LotArea', '1stFlrSF', 'GrLivArea', 'SalePrice']
categoricals = ['BldgType', 'KitchenQual', 'SaleType', 'MSZoning', 'Street', 'Neighborhood']

ames_cont = ames[continuous]

# log features
log_names = [f'{column}_log' for column in ames_cont.columns]

ames_log = np.log(ames_cont)
ames_log.columns = log_names

# normalize (subract mean and divide by std)

def normalize(feature):
    return (feature - feature.mean()) / feature.std()

ames_log_norm = ames_log.apply(normalize)

# one hot encode categoricals
ames_ohe = pd.get_dummies(ames[categoricals], prefix=categoricals, drop_first=True)

preprocessed = pd.concat([ames_log_norm, ames_ohe], axis=1)
preprocessed.head()

LotArea_log  1stFlrSF_log  GrLivArea_log  SalePrice_log  BldgType_2fmCon  \
0    -0.133185     -0.803295       0.529078       0.559876                0   
1     0.113403      0.418442      -0.381715       0.212692                0   
2     0.419917     -0.576363       0.659449       0.733795                0   
3     0.103311     -0.439137       0.541326      -0.437232                0   
4     0.878108      0.112229       1.281751       1.014303                0   

   BldgType_Duplex  BldgType_Twnhs  BldgType_TwnhsE  KitchenQual_Fa  \
0                0               0                0               0   
1                0               0                0               0   
2                0               0                0               0   
3                0               0                0               0   
4                0               0                0               0   

   KitchenQual_Gd  ...  Neighborhood_NoRidge  Neighborhood_NridgHt  \
0               1  ...                     0                     0   
1               0  ...                     0                     0   
2               1  ...                     0                     0   
3               1  ...                     0                     0   
4               1  ...                     1                     0   

   Neighborhood_OldTown  Neighborhood_SWISU  Neighborhood_Sawyer  \
0                     0                   0                    0   
1                     0                   0                    0   
2                     0                   0                    0   
3                     0                   0                    0   
4                     0                   0                    0   

   Neighborhood_SawyerW  Neighborhood_Somerst  Neighborhood_StoneBr  \
0                     0                     0                     0   
1                     0                     0                     0   
2                     0                     0                     0   
3                     0                     0                     0   
4                     0                     0                     0   

   Neighborhood_Timber  Neighborhood_Veenker  
0                    0                     0  
1                    0                     1  
2                    0                     0  
3                    0                     0  
4                    0                     0  

[5 rows x 48 columns]

## Perform stepwise selection

The function for stepwise selection is copied below. Use this function provided on your preprocessed Boston Housing data.

In [11]:
import statsmodels.api as sm

def stepwise_selection(X, y, 
                       initial_list=[], 
                       threshold_in=0.01, 
                       threshold_out = 0.05, 
                       verbose=False):
    """ Perform a forward-backward feature selection 
    based on p-value from statsmodels.api.OLS
    Arguments:
        X - pandas.DataFrame with candidate features
        y - list-like with the target
        initial_list - list of features to start with (column names of X)
        threshold_in - include a feature if its p-value < threshold_in
        threshold_out - exclude a feature if its p-value > threshold_out
        verbose - whether to print the sequence of inclusions and exclusions
    Returns: list of selected features 
    Always set threshold_in < threshold_out to avoid infinite looping.
    See https://en.wikipedia.org/wiki/Stepwise_regression for the details
    """
    included = list(initial_list)
    while True:
        changed=False
        # forward step
        excluded = list(set(X.columns)-set(included))
        new_pval = pd.Series(index=excluded, dtype = 'float64')
        for new_column in excluded:
            model = sm.OLS(y, sm.add_constant(pd.DataFrame(X[included+[new_column]]))).fit()
            new_pval[new_column] = model.pvalues[new_column]
        best_pval = new_pval.min()
        if best_pval < threshold_in:
            best_feature = new_pval.idxmin()
            included.append(best_feature)
            changed=True
            if verbose:
                print('Add  {:30} with p-value {:.6}'.format(best_feature, best_pval))

        # backward step
        model = sm.OLS(y, sm.add_constant(pd.DataFrame(X[included]))).fit()
        # use all coefs except intercept
        pvalues = model.pvalues.iloc[1:]
        worst_pval = pvalues.max() # null if pvalues is empty
        if worst_pval != None:
            if worst_pval > threshold_out:
                changed=True
                worst_feature = pvalues.loc[pvalues == pvalues.max()].index[0]
                included.remove(worst_feature)
                if verbose:
                    print('Drop {:30} with p-value {:.6}'.format(worst_feature, worst_pval))
        if not changed:
            break
    return included

In [12]:
impactfulColumns = stepwise_selection(preprocessed, preprocessed['SalePrice_log'])

### Build the final model again in Statsmodels

In [36]:
# Import statsmodels.api as sm
from statsmodels.formula.api import ols
dfFinal = preprocessed[impactfulColumns]
outcome = 'SalePrice_log'
predictors = dfFinal.drop(['SalePrice_log'], axis=1)
pred_sum = '+'.join(predictors.columns)
formula = outcome + '~' + pred_sum

In [37]:
model = ols(formula=formula, data=dfFinal).fit()
model.summary()

SyntaxError: invalid syntax (<unknown>, line 1)

## Use Feature ranking with recursive feature elimination

Use feature ranking to select the 5 most important features

In [45]:
#from sklearn.datasets import make_friedman1
from sklearn.feature_selection import RFE
from sklearn.linear_model import LinearRegression

linreg = LinearRegression()
selector = RFE(linreg, n_features_to_select=5)
selector = selector.fit(preprocessed, preprocessed['SalePrice_log'])

Fit the linear regression model again using the 5 selected columns

In [46]:
estimators = selector.estimator_
display(selector.support_ ,
        selector.ranking_,
       estimators.coef_,
       estimators.intercept_)

array([False, False,  True,  True,  True, False, False, False, False,
       False, False, False, False,  True, False, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False])

array([23,  9,  1,  1,  1,  6, 24,  3, 41, 30,  5,  4,  7,  1, 44, 35, 21,
       43, 28, 40, 25,  1,  2,  8, 14, 42, 39, 18, 29, 11, 38, 15, 12, 31,
       37, 19, 10, 22, 33, 13, 20, 34, 26, 17, 27, 16, 36, 32])

array([-9.30106249e-17,  1.00000000e+00, -2.65339562e-17, -7.47122994e-17,
        3.22123706e-16])

-2.529242617256421e-16

Now, predict $\hat y$ using your model. You can use `.predict()` in scikit-learn. 

In [54]:
selected_columns = preprocessed.columns[selector.support_ ]
linreg.fit(preprocessed[selected_columns],preprocessed['SalePrice_log'])
yhat = linreg.predict(preprocessed[selected_columns])
np.exp(yhat).max()

43.87026947057711

Now, using the formulas of R-squared and adjusted R-squared below, and your Python/numpy knowledge, compute them and contrast them with the R-squared and adjusted R-squared in your statsmodels output using stepwise selection. Which of the two models would you prefer?

$SS_{residual} = \sum (y - \hat{y})^2 $

$SS_{total} = \sum (y - \bar{y})^2 $

$R^2 = 1- \dfrac{SS_{residual}}{SS_{total}}$

$R^2_{adj}= 1-(1-R^2)\dfrac{n-1}{n-p-1}$

In [8]:
# Your code here

# r_squared is 0.239434  
# adjusted_r_squared is 0.236818

## Level up (Optional)

- Perform variable selection using forward selection, using this resource: https://planspace.org/20150423-forward_selection_with_statsmodels/. Note that this time features are added based on the adjusted R-squared!
- Tweak the code in the `stepwise_selection()` function written above to just perform forward selection based on the p-value 

## Summary
Great! You practiced your feature selection skills by applying stepwise selection and recursive feature elimination to the Ames Housing dataset! 